/**
 * synthesize_shelves — Cordelia's nightly distill pass as a job-only tool
 * (consolidation cycle Phase 1, 2026-06-14).
 *
 * A thin tool wrapper over `synthesize_shelves()` in ../shelf_synthesis.ts,
 * wired the same YAML-driven way as `refresh_subscriptions` /
 * `advance_research_commissions`: it runs as the `nightly_shelf_synthesis`
 * background job (config/specialists/cordelia.yaml, 04:20 — after the night's
 * acquisition has settled) and is deliberately OFF her LLM chat/deliberation
 * surfaces. Manual catch-up:
 *   POST /api/specialists/cordelia/fire_background_job?name=nightly_shelf_synthesis&wait=1
 *
 * Kill switch HEARTH_SHELF_SYNTHESIS=0 disables the pass (enabled:false).
 */
import { z } from 'zod';
import type { Tool, ToolContext } from '@core/tool';
import type { ToolDeps } from '@core/tool_deps';
import {
  synthesize_shelves,
  type ShelfSynthesisDeps,
} from '../shelf_synthesis';
import { heal_syntheses } from '../synthesis_heal';

const InputSchema = z.object({
  force: z
    .boolean()
    .default(false)
    .describe(
      'Re-cluster every shelf regardless of whether new items landed since ' +
        'the last pass (still idempotent — unchanged topics skip the LLM). For ' +
        'a first-run populate or catch-up.',
    ),
  max_shelves: z
    .number()
    .int()
    .min(1)
    .max(40)
    .default(12)
    .describe('Per-run cap on shelves processed (nightly fairness; paired with the wall-clock deadline).'),
  min_items_per_topic: z
    .number()
    .int()
    .min(2)
    .max(20)
    .default(3)
    .describe('A topic cluster smaller than this is left as-is (a single capture is already its own note).'),
});

const OutputSchema = z.object({
  enabled: z.boolean(),
  shelves_scanned: z.number(),
  shelves_synthesized: z.number(),
  syntheses_written: z.number(),
  topics_skipped_unchanged: z.number(),
  topics_below_min: z.number(),
  distill_failures: z.number(),
  grounding_corrected: z.number(),
  grounding_reduced: z.number(),
  grounding_rejected: z.number(),
  notes: z.array(z.string()),
  skipped_reason: z.string().optional(),
  // Self-heal pass (#3) — runs BEFORE the distill below; its rot deletions +
  // shelf resets are regenerated by this same run.
  heal: z.object({
    enabled: z.boolean(),
    scanned: z.number(),
    resynthesize_queued: z.number(),
    pruned_dead_weight: z.number(),
    shelves_reset: z.array(z.string()),
  }),
});

type Input = z.infer<typeof InputSchema>;
type Output = z.infer<typeof OutputSchema>;

export function make_synthesize_shelves(deps: ShelfSynthesisDeps): Tool<Input, Output> {
  return {
    name: 'synthesize_shelves',
    description:
      'Consolidate each library shelf\'s accumulating raw notes into compact, cited, evergreen syntheses — your nightly distill pass. Buckets each shelf by visibility, clusters by topic, and distills each topic into a "what we know" note that becomes a high-signal search hit. Idempotent (unchanged topics skip the LLM) and cordon-safe (a synthesis never mixes visibility buckets). Runs as your background job; call manually only for a catch-up (e.g. {force: true}).',
    risk: 'write_internal',
    required_capabilities: ['write_vault_any_library'],
    input_schema: InputSchema,
    output_schema: OutputSchema,
    // Result depends on shelf + store state the run itself mutates — a repeat
    // call must re-run, not re-serve the per-turn duplicate cache.
    volatile: true,

    idempotency_key(input) {
      return `synthesize_shelves:${input.force ? 'force' : 'due'}:${input.max_shelves}`;
    },

    async execute(input, ctx: ToolContext): Promise<Output> {
      const now = ctx.now ?? new Date();
      // Heal FIRST — delete integrity-rotted syntheses and reset their shelves
      // so the distill pass right below regenerates them from surviving sources
      // in this same run; prune dead weight. Fail-open: a heal error must not
      // block the night's distillation.
      let heal;
      try {
        heal = await heal_syntheses(deps, { now });
      } catch (err) {
        console.error('[synthesize_shelves] heal pass failed (non-fatal):', err);
        heal = {
          enabled: true,
          scanned: 0,
          resynthesize_queued: 0,
          pruned_dead_weight: 0,
          shelves_reset: [],
        };
      }
      const syn = await synthesize_shelves(deps, {
        now,
        force: input.force,
        max_shelves: input.max_shelves,
        min_items_per_topic: input.min_items_per_topic,
      });
      return {
        ...syn,
        heal: {
          enabled: heal.enabled,
          scanned: heal.scanned,
          resynthesize_queued: heal.resynthesize_queued,
          pruned_dead_weight: heal.pruned_dead_weight,
          shelves_reset: heal.shelves_reset,
        },
      };
    },
  };
}

export function create(deps: ToolDeps): Tool {
  return make_synthesize_shelves({
    library_deps: {
      db: deps.db,
      vault_root: deps.vault_root,
      memory: deps.memory,
      specialists: deps.specialists,
      runtime: deps.runtime,
      conversations: deps.conversations,
      llm: deps.llm,
      embedder: deps.embedder,
      events: deps.events,
    },
  }) as Tool;
}
