/**
 * update_taste_profile — overwrite Maggie's living taste-profile snapshot.
 *
 * Unlike update_maggie_memory (append-only, log-shaped), this tool
 * REPLACES the contents of Knowledge/Maggie/taste_profile.md each time
 * it's called. The taste profile is a single living document — Maggie's
 * synthesized view of what Jasper's been into lately. It's regenerated
 * by the 04:00 deliberation pass (weekly cadence in effect, daily slot
 * — the persona gates by day-of-week internally) from a depth-model
 * synthesis of:
 *
 *   - the last 30d of Plex consumption (movies + TV)
 *   - the last 30d of Apple Music plays (when Phase 2 lands)
 *   - the last ~50 chat taste-mention entries from memory.md
 *
 * The Phase-5 thematic-recommendation pass reads this profile (via
 * search_library) to drive "what should we add" reasoning.
 *
 * Capability: write_vault_media (same as update_maggie_memory). Path is
 * hardcoded under Knowledge/Maggie/ so the grant can't reach past her
 * own namespace.
 */

import { z } from 'zod';
import { createHash } from 'node:crypto';
import { ulid } from 'ulid';
import { writeFileSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import type { Tool, ToolContext } from '@core/tool';
import type { ToolDeps } from '@core/tool_deps';

const REL_PATH = 'Knowledge/Maggie/taste_profile.md';

const InputSchema = z.object({
  body: z
    .string()
    .min(50)
    .max(20_000)
    .describe(
      "The full markdown body of the taste profile (REPLACES whatever's " +
        'there). Expected to be a depth-model synthesis with sections like ' +
        '## Cinema affinity, ## TV affinity, ## Music affinity, ## What to ' +
        'chase. The tool wraps with a header + timestamp; just pass the ' +
        'section bodies.',
    ),
  notes: z
    .string()
    .max(500)
    .default('')
    .describe(
      'Optional one-line note about what changed vs the prior profile or ' +
        "what depth-model question was asked. Appears under 'Generation notes' " +
        'at the end of the file. For audit, not user-facing in normal flow.',
    ),
});

const OutputSchema = z.object({
  rel_path: z.string(),
  bytes_written: z.number(),
  generated_at: z.string(),
});

type Input = z.infer<typeof InputSchema>;
type Output = z.infer<typeof OutputSchema>;

function render(body: string, notes: string, now: Date): string {
  const ts = now.toISOString();
  const intro =
    `# Jasper's media taste profile\n\n` +
    `_Living snapshot of Jasper's media taste — regenerated by Maggie's ` +
    `weekly synthesis pass at the 04:00 deliberation slot. Most-recent ` +
    `synthesis wins; this file is OVERWRITTEN, not appended. Phase 5's ` +
    `thematic-recommendation pass reads it via search_library to drive ` +
    `"what should we add" reasoning._\n\n` +
    `_Last regenerated: ${ts}_\n\n---\n\n`;
  const notes_block = notes
    ? `\n\n---\n\n## Generation notes\n\n_${notes.trim()}_\n`
    : '';
  return intro + body.trim() + notes_block + '\n';
}

export function create(deps: ToolDeps): Tool<Input, Output> {
  return {
    name: 'update_taste_profile',
    description:
      "Overwrite Maggie's living taste-profile snapshot at " +
      'Knowledge/Maggie/taste_profile.md with a fresh depth-model synthesis. ' +
      "Unlike update_maggie_memory (append-only log), this REPLACES the " +
      'file each call — the profile is a single living document, not a log. ' +
      'Use ONLY from the 04:00 deliberation synthesis workflow, after ' +
      'pulling Plex + (when available) music signals and handing them to ' +
      '`consult_deep_model`. Take the depth response as `body`; pass an ' +
      'optional `notes` line for audit.',
    risk: 'write_internal',
    required_capabilities: ['write_vault_media'],
    input_schema: InputSchema,
    output_schema: OutputSchema,

    idempotency_key(input) {
      const h = createHash('sha256');
      h.update(input.body);
      h.update('\n');
      h.update(input.notes);
      return `update_taste_profile:${h.digest('hex').slice(0, 16)}`;
    },

    async execute(input, ctx: ToolContext): Promise<Output> {
      const abs = resolve(deps.vault_root, REL_PATH);
      mkdirSync(dirname(abs), { recursive: true });
      const now = ctx.now ?? new Date();
      const text = render(input.body, input.notes, now);
      writeFileSync(abs, text, 'utf8');

      ctx.memory.log_action({
        intent_id: ctx.intent_id || ulid(),
        agent: ctx.specialist_id ?? 'maggie',
        tool_name: 'update_taste_profile',
        tool_input: { body_chars: input.body.length, notes_chars: input.notes.length },
        execution_result: { rel_path: REL_PATH, bytes_written: text.length },
      });

      return {
        rel_path: REL_PATH,
        bytes_written: text.length,
        generated_at: now.toISOString(),
      };
    },
  };
}
