/**
 * Idempotent: seed ~/vault-friday/Places/ with Home.md if the directory
 * is empty (or doesn't exist yet). Gives the ingestor something to
 * project on first run, and acts as an example for Jasper of what a
 * Place note looks like.
 */

import { existsSync, mkdirSync, writeFileSync, readdirSync } from 'node:fs';
import { resolve } from 'node:path';
import matter from 'gray-matter';
import { randomBytes } from 'node:crypto';

const VAULT_ROOT =
  process.env.HEARTH_VAULT_ROOT ?? `${process.env.HOME}/vault-friday`;

const places_dir = resolve(VAULT_ROOT, 'Places');

function gen_place_id(): string {
  const ALPHA = 'abcdefghijklmnopqrstuvwxyz234567';
  const bytes = randomBytes(6);
  let out = 'pl_';
  for (let i = 0; i < 6; i++) {
    out += ALPHA[bytes[i]! % 32];
  }
  return out;
}

function run(): void {
  mkdirSync(places_dir, { recursive: true });

  const has_any = readdirSync(places_dir).some((f) => f.endsWith('.md'));
  if (has_any) {
    console.log(`[init-places] Places/ already populated — nothing to do.`);
    return;
  }

  const home_path = resolve(places_dir, 'Home.md');
  const fm = {
    type: 'place',
    id: gen_place_id(),
    name: 'Home',
    aliases: ['the house', 'home'],
    address: '3215 Westwood Ct, Pleasantville, CO 80000',
    coords: null,
    category: 'residence',
    ha_zone_name: 'home',
    parking_buffer_minutes: 0,
  };
  const body = `
# Home

3215 Westwood Ct, Pleasantville, CO.

## How places work

Each significant location lives as a markdown file under \`Places/\` with
structured frontmatter. The ingestor projects them into the SQLite
\`places\` table so Kate and Iris can look them up quickly.

Frontmatter fields:

- \`type: place\` — required, marks the note for projection.
- \`id: pl_xxxxxx\` — auto-generated by the upsert_place tool.
- \`name\` — primary display name.
- \`aliases\` — alternate names Kate / Iris can recognize.
- \`address\` — street address; geocoded on first resolve.
- \`coords: [lat, lon]\` — cached after first geocode (or null).
- \`category\` — e.g. \`veterinary\`, \`grocery\`, \`charging\`, \`residence\`.
- \`ha_zone_name\` — name of the matching Home Assistant zone (see
  \`integrations/home_assistant/ZONES.md\`).
- \`parking_buffer_minutes\` — added to ETAs when this is the
  destination (the time-to-park-and-walk-in delta).
- \`hours\` — optional \`{weekday: "HH:MM-HH:MM"}\`.
- \`phone\` — optional contact.
- \`notes\` — free-form; parking instructions, who you usually see there.

## Adding more places

The cleanest path is to mention a place in conversation with Kate, Iris,
or Eleanor — they have the \`write_places\` capability and the
\`upsert_place\` tool. They'll geocode the address, link it to a Home
Assistant zone if one exists, and accumulate observations over time
into the \`notes\` field.

You can also create them by hand in Obsidian. The ingestor picks up
new files within ~500 ms.
`.trimStart();

  writeFileSync(home_path, matter.stringify(body, fm), 'utf8');
  console.log(`[init-places] seeded ${home_path}`);
}

run();
